In [57]:
import numpy as np
import pandas as pd

**Overdoses**

In [58]:
overdoses = pd.read_csv("./datasets_monthly/VSRR_Provisional_Drug_Overdose_Death_Counts.csv", sep = ",")
#overdoses

In [59]:
overdoses1 = overdoses.loc[(overdoses["State Name"] == "United States") & (overdoses["Indicator"] != "Percent with drugs specified") & (overdoses["Indicator"] != "Number of Deaths")]
#overdoses1

In [60]:
overdoses1 = overdoses1.drop(columns=["State", "Period", "Percent Complete", "Percent Pending Investigation", "State Name", "Footnote", "Footnote Symbol", "Predicted Value"])

overdoses1 = overdoses1.astype({'Data Value': 'int64'})

overdoses1.dtypes

Year           int64
Month         object
Indicator     object
Data Value     int64
dtype: object

In [63]:
overdoses2 = overdoses1

overdoses2 = overdoses2.pivot(index = ['Year', 'Month'], columns ='Indicator', values = 'Data Value')

meses = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
overdoses2 = overdoses2.reindex(pd.MultiIndex.from_product([overdoses2.index.levels[0], meses], names=['Year', 'Month']))

overdoses2.head(-1)
#overdoses2.to_csv('./overdoses.csv', index = True)

Indicator       Cocaine (T40.5)  Heroin (T40.1)  Methadone (T40.3)  \
Year Month
2015 January             5496.0         10788.0             3413.0
     February            5592.0         11002.0             3372.0
     March               5729.0         11167.0             3387.0
     April               5908.0         11471.0             3401.0
     May                 5987.0         11675.0             3421.0
...                         ...             ...                ...
2020 July               18997.0         14145.0             3234.0
     August             19021.0         13905.0             3313.0
     September              NaN             NaN                NaN
     October                NaN             NaN                NaN
     November               NaN             NaN                NaN

Indicator       Natural & semi-synthetic opioids (T40.2)  \
Year Month
2015 January                                     12269.0
     February                                    12237.0
     March                                       12267.0
     April                                       12356.0
     May                                         12474.0
...                                                  ...
2020 July                                        12894.0
     August                                      12986.0
     September                                       NaN
     October                                         NaN
     November                                        NaN

Indicator       Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)  \
Year Month
2015 January                                              14944.0
     February                                             14885.0
     March                                                14929.0
     April                                                15022.0
     May                                                  15133.0
...                                                           ...
2020 July                                                 15593.0
     August                                               15750.0
     September                                                NaN
     October                                                  NaN
     November                                                 NaN

Indicator       Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)  \
Year Month
2015 January                                              19161.0
     February                                             19358.0
     March                                                19640.0
     April                                                20124.0
     May                                                  20539.0
...                                                           ...
2020 July                                                 56943.0
     August                                               58414.0
     September                                                NaN
     October                                                  NaN
     November                                                 NaN

Indicator       Number of Drug Overdose Deaths  Opioids (T40.0-T40.4,T40.6)  \
Year Month
2015 January                           47523.0                      28986.0
     February                          47725.0                      29269.0
     March                             48198.0                      29609.0
     April                             48748.0                      30240.0
     May                               49293.0                      30745.0
...                                        ...                          ...
2020 July                              83989.0                      61626.0
     August                            85516.0                      62972.0
     September                             NaN                          NaN
     October                               NaN                          NaN
     November                              NaN                          NaN

Indicator       Psychostimulants with abuse potential (T43.6)  \
Year Month
2015 January                                           4402.0
     February                                          4449.0
     March                                             4586.0
     April                                             4675.0
     May                                               4785.0
...                                                       ...
2020 July                                             20539.0
     August                                           21405.0
     September                                            NaN
     October                                              NaN
     November                                             NaN

Indicator       Synthetic opioids, excl. methadone (T40.4)
Year Month
2015 January                                        5766.0
     February                                       6079.0
     March                                          6390.0
     April                                          6868.0
     May                                            7254.0
...                                                    ...
2020 July                                          48987.0
     August                                        50492.0
     September                                         NaN
     October                                           NaN
     November                                          NaN

[71 rows x 10 columns]

**VÃ¡rias causas e as respetivas mortes por mÃªs**

In [35]:
deaths = pd.read_csv("./datasets_monthly/Monthly_Counts_of_Deaths_by_Select_Causes__2020-2021.csv", sep = ",")

deaths

,Data As Of,Start Date,End Date,Jurisdiction of Occurrence,Year,Month,All Cause,Natural Cause,Septicemia,Malignant Neoplasms,...,Intentional Self-Harm (Suicide),Assault (Homicide),Drug Overdose,COVID-19 (Multiple Cause of Death),COVID-19 (Underlying Cause of Death),flag_accid,flag_mva,flag_suic,flag_homic,flag_drugod
0,04/07/2021,01/01/2020,01/31/2020,United States,2020,1,264620,242896,3698,52632,...,4035.0,1701.0,6488.0,5,4,NaN,NaN,NaN,NaN,NaN
1,04/07/2021,02/01/2020,02/29/2020,United States,2020,2,244871,224305,3344,48765,...,3651.0,1470.0,6372.0,16,15,NaN,NaN,NaN,NaN,NaN
2,04/07/2021,03/01/2020,03/31/2020,United States,2020,3,269728,247612,3689,51654,...,3941.0,1684.0,7201.0,7095,6717,NaN,NaN,NaN,NaN,NaN
3,04/07/2021,04/01/2020,04/30/2020,United States,2020,4,322351,300803,3384,48772,...,3456.0,1754.0,7833.0,65239,61745,NaN,NaN,NaN,NaN,NaN
4,04/07/2021,05/01/2020,05/31/2020,United States,2020,5,280452,255562,3095,49004,...,3751.0,2055.0,9281.0,38190,35144,NaN,NaN,NaN,NaN,NaN
5,04/07/2021,06/01/2020,06/30/2020,United States,2020,6,250303,225567,3047,47954,...,3963.0,2229.0,7984.0,17910,15744,NaN,NaN,NaN,NaN,NaN
6,04/07/2021,07/01/2020,07/31/2020,United States,2020,7,278811,252685,3149,50615,...,4134.0,2396.0,8252.0,30989,28163,NaN,NaN,NaN,NaN,NaN
7,04/07/2021,08/01/2020,08/31/2020,United States,2020,8,277062,251410,3285,51192,...,3995.0,2312.0,7927.0,29732,26912,NaN,NaN,NaN,NaN,NaN
8,04/07/2021,09/01/2020,09/30/2020,United States,2020,9,256880,233046,3156,49646,...,3871.0,2131.0,7206.0,19028,16762,NaN,NaN,NaN,NaN,NaN
9,04/07/2021,10/01/2020,10/31/2020,United States,2020,10,271979,248344,3255,50912,...,NaN,NaN,NaN,24582,21806,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)
10,04/07/2021,11/01/2020,11/30/2020,United States,2020,11,299631,277367,3373,49164,...,NaN,NaN,NaN,52579,47499,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)
11,04/07/2021,12/01/2020,12/31/2020,United States,2020,12,356322,334692,3653,50296,...,NaN,NaN,NaN,95594,87384,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)
12,04/07/2021,01/01/2021,01/31/2021,United States,2021,1,352599,333663,3460,49099,...,NaN,NaN,NaN,98759,90434,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)
13,04/07/2021,02/01/2021,02/28/2021,United States,2021,2,258164,244751,3058,42684,...,NaN,NaN,NaN,44157,39108,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)
14,04/07/2021,03/01/2021,03/31/2021,United States,2021,3,174561,168179,2022,33405,...,NaN,NaN,NaN,15606,13476,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)
15,04/07/2021,04/01/2021,04/03/2021,United States,2021,4,2923,2879,30,656,...,NaN,NaN,NaN,252,233,Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag),Data not shown (6 month lag)

**Mortes por covid, incluindo internamentos**

In [132]:
data_covid = pd.read_csv("./datasets_monthly/data.csv", sep = ",")

data_covid

,data,data_dados,confirmados,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,...,obitos_m,confirmados_desconhecidos_m,confirmados_desconhecidos_f,ativos,internados_enfermaria,confirmados_desconhecidos,incidencia_nacional,incidencia_continente,rt_nacional,rt_continente
0,26-02-2020,26-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27-02-2020,27-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28-02-2020,28-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29-02-2020,29-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-03-2020,01-03-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,17-04-2021,17-04-2021 00:00,830560,333542,118079,314568,29554,21348,4507,8962,...,8903.0,NaN,NaN,25344.0,312.0,302.0,71.6,68.0,1.05,1.04
417,18-04-2021,18-04-2021 00:00,831001,333735,118125,314677,29559,21386,4540,8979,...,8903.0,NaN,NaN,25387.0,319.0,302.0,71.6,68.0,1.05,1.04
418,19-04-2021,19-04-2021 00:00,831221,333832,118149,314733,29568,21391,4554,8994,...,8903.0,NaN,NaN,25059.0,342.0,302.0,71.8,68.1,1.00,1.00
419,20-04-2021,20-04-2021 00:00,831645,333961,118183,314886,29609,21419,4570,9017,...,8906.0,NaN,NaN,24576.0,316.0,305.0,71.8,68.1,1.00,1.00
420,21-04-2021,21-04-2021 00:00,832255,334246,118236,315075,29625,21438,4599,9036,...,8906.0,NaN,NaN,24653.0,287.0,303.0,72.7,68.9,0.98,0.99

In [157]:
data_covid1 = data_covid.drop(columns=['data_dados', 'confirmados', 'confirmados_estrangeiro', 'lab', 'suspeitos', 'vigilancia',
                                        'n_confirmados', 'cadeias_transmissao', 'transmissao_importada',
                                        'obitos_estrangeiro', 'recuperados_arsnorte','recuperados_arscentro',
                                        'recuperados_arslvt','recuperados_arsalentejo',
                                        'recuperados_arsalgarve','recuperados_acores', 'recuperados_madeira',
                                        'recuperados_estrangeiro','confirmados_desconhecidos_m','confirmados_desconhecidos_f',
                                        'incidencia_nacional','incidencia_continente','rt_nacional', 'rt_continente',
                                        'obitos_f', 'obitos_m','confirmados_desconhecidos','confirmados_f','confirmados_m'], inplace=False)
data_covid1.head()

,data,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
0,26-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-03-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,17-04-2021,333542,118079,314568,29554,21348,4507,8962,649,788274,...,130.0,331.0,459.0,1057.0,1326.0,2274.0,6035.0,5120.0,25344.0,312.0
417,18-04-2021,333735,118125,314677,29559,21386,4540,8979,441,788669,...,130.0,331.0,459.0,1057.0,1328.0,2274.0,6036.0,5120.0,25387.0,319.0
418,19-04-2021,333832,118149,314733,29568,21391,4554,8994,220,789216,...,130.0,331.0,459.0,1057.0,1328.0,2274.0,6037.0,5120.0,25059.0,342.0
419,20-04-2021,333961,118183,314886,29609,21419,4570,9017,424,790118,...,130.0,331.0,460.0,1058.0,1328.0,2276.0,6038.0,5120.0,24576.0,316.0
420,21-04-2021,334246,118236,315075,29625,21438,4599,9036,610,790650,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24653.0,287.0

In [162]:
data_covid1.columns = ['Date', 'confirmados_arsnorte', 'confirmados_arscentro','confirmados_arslvt', 'confirmados_arsalentejo', 'confirmados_arsalgarve', 'confirmados_acores', 'confirmados_madeira','confirmados_novos', 'recuperados', 'obitos', 'internados', 'internados_uci','confirmados_0_9_f', 'confirmados_0_9_m', 'confirmados_10_19_f', 'confirmados_10_19_m', 'confirmados_20_29_f', 'confirmados_20_29_m', 'confirmados_30_39_f', 'confirmados_30_39_m', 'confirmados_40_49_f', 'confirmados_40_49_m', 'confirmados_50_59_f', 'confirmados_50_59_m', 'confirmados_60_69_f', 'confirmados_60_69_m', 'confirmados_70_79_f', 'confirmados_70_79_m', 'confirmados_80_plus_f', 'confirmados_80_plus_m', 'sintomas_tosse', 'sintomas_febre', 'sintomas_dificuldade_respiratoria', 'sintomas_cefaleia', 'sintomas_dores_musculares', 'sintomas_fraqueza_generalizada', 'obitos_arsnorte', 'obitos_arscentro', 'obitos_arslvt', 'obitos_arsalentejo', 'obitos_arsalgarve', 'obitos_acores', 'obitos_madeira', 'obitos_0_9_f', 'obitos_0_9_m', 'obitos_10_19_f', 'obitos_10_19_m', 'obitos_20_29_f', 'obitos_20_29_m', 'obitos_30_39_f', 'obitos_30_39_m', 'obitos_40_49_f', 'obitos_40_49_m', 'obitos_50_59_f', 'obitos_50_59_m', 'obitos_60_69_f', 'obitos_60_69_m', 'obitos_70_79_f', 'obitos_70_79_m', 'obitos_80_plus_f', 'obitos_80_plus_m', 'ativos', 'internados_enfermaria']
data_covid1

,Date,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
0,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,2020-02-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,2021-04-17,258.0,52.0,198.0,43.0,47.0,33.0,18.0,649,667.0,...,0.0,0.0,1.0,1.0,0.0,0.0,2.0,1.0,25344.0,312.0
417,2021-04-18,193.0,46.0,109.0,5.0,38.0,33.0,17.0,441,395.0,...,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,25387.0,319.0
418,2021-04-19,97.0,24.0,56.0,9.0,5.0,14.0,15.0,220,547.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,25059.0,342.0
419,2021-04-20,129.0,34.0,153.0,41.0,28.0,16.0,23.0,424,902.0,...,0.0,0.0,1.0,1.0,0.0,2.0,1.0,0.0,24576.0,316.0
420,2021-04-21,285.0,53.0,189.0,16.0,19.0,29.0,19.0,610,532.0,...,-130.0,-331.0,-460.0,-1058.0,-1328.0,-2276.0,-6038.0,-5120.0,24653.0,287.0

In [163]:
data_covid1 = data_covid1.fillna(0)
data_covid1.head()

,Date,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
0,2020-02-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-02-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [165]:
data_covid1['Date'] = pd.to_datetime(data_covid1['Date'],format="%d-%m-%Y")

data_covid1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 64 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               421 non-null    datetime64[ns]
 1   confirmados_arsnorte               421 non-null    float64
 2   confirmados_arscentro              421 non-null    float64
 3   confirmados_arslvt                 421 non-null    float64
 4   confirmados_arsalentejo            421 non-null    float64
 5   confirmados_arsalgarve             421 non-null    float64
 6   confirmados_acores                 421 non-null    float64
 7   confirmados_madeira                421 non-null    float64
 8   confirmados_novos                  421 non-null    int64
 9   recuperados                        421 non-null    float64
 10  obitos                             421 non-null    float64
 11  internados                         421 non-null    float64
 12  internados_uci                     421 non-null    float64
 13  confirmados_0_9_f                  421 non-null    float64
 14  confirmados_0_9_m                  421 non-null    float64
 15  confirmados_10_19_f                421 non-null    float64
 16  confirmados_10_19_m                421 non-null    float64
 17  confirmados_20_29_f                421 non-null    float64
 18  confirmados_20_29_m                421 non-null    float64
 19  confirmados_30_39_f                421 non-null    float64
 20  confirmados_30_39_m                421 non-null    float64
 21  confirmados_40_49_f                421 non-null    float64
 22  confirmados_40_49_m                421 non-null    float64
 23  confirmados_50_59_f                421 non-null    float64
 24  confirmados_50_59_m                421 non-null    float64
 25  confirmados_60_69_f                421 non-null    float64
 26  confirmados_60_69_m                421 non-null    float64
 27  confirmados_70_79_f                421 non-null    float64
 28  confirmados_70_79_m                421 non-null    float64
 29  confirmados_80_plus_f              421 non-null    float64
 30  confirmados_80_plus_m              421 non-null    float64
 31  sintomas_tosse                     421 non-null    float64
 32  sintomas_febre                     421 non-null    float64
 33  sintomas_dificuldade_respiratoria  421 non-null    float64
 34  sintomas_cefaleia                  421 non-null    float64
 35  sintomas_dores_musculares          421 non-null    float64
 36  sintomas_fraqueza_generalizada     421 non-null    float64
 37  obitos_arsnorte                    421 non-null    float64
 38  obitos_arscentro                   421 non-null    float64
 39  obitos_arslvt                      421 non-null    float64
 40  obitos_arsalentejo                 421 non-null    float64
 41  obitos_arsalgarve                  421 non-null    float64
 42  obitos_acores                      421 non-null    float64
 43  obitos_madeira                     421 non-null    float64
 44  obitos_0_9_f                       421 non-null    float64
 45  obitos_0_9_m                       421 non-null    float64
 46  obitos_10_19_f                     421 non-null    float64
 47  obitos_10_19_m                     421 non-null    float64
 48  obitos_20_29_f                     421 non-null    float64
 49  obitos_20_29_m                     421 non-null    float64
 50  obitos_30_39_f                     421 non-null    float64
 51  obitos_30_39_m                     421 non-null    float64
 52  obitos_40_49_f                     421 non-null    float64
 53  obitos_40_49_m                     421 non-null    float64
 54  obitos_50_59_f                     421 non-null    float64
 55  obitos_50_59_m                     421 non-null    float64
 56  obitos_60_69_f                     421 non-null    float64
 57  obitos_60_69_m                     421 non-null    float64
 58  obitos_70_79_f                     421 non-null    float64
 59  obitos_70_79_m                     421 non-null    float64
 60  obitos_80_plus_f                   421 non-null    float64
 61  obitos_80_plus_m                   421 non-null    float64
 62  ativos                             421 non-null    float64
 63  internados_enfermaria              421 non-null    float64
dtypes: datetime64[ns](1), float64(62), int64(1)
memory usage: 210.6 KB

In [166]:
data_covid1["confirmados_arsnorte"] = data_covid1.loc[:,["confirmados_arsnorte"]].diff()
data_covid1["confirmados_arscentro"] = data_covid1.loc[:,["confirmados_arscentro"]].diff()
data_covid1["confirmados_arslvt"] = data_covid1.loc[:,["confirmados_arslvt"]].diff()
data_covid1["confirmados_arsalentejo"] = data_covid1.loc[:,["confirmados_arsalentejo"]].diff()
data_covid1["confirmados_arsalgarve"] = data_covid1.loc[:,["confirmados_arsalgarve"]].diff()
data_covid1["confirmados_acores"] = data_covid1.loc[:,["confirmados_acores"]].diff()
data_covid1["confirmados_madeira"] = data_covid1.loc[:,["confirmados_madeira"]].diff()
data_covid1["recuperados"] = data_covid1.loc[:,["recuperados"]].diff()
data_covid1["obitos"] = data_covid1.loc[:,["obitos"]].diff()
data_covid1["confirmados_0_9_m"] = data_covid1.loc[:,["confirmados_0_9_m"]].diff()
data_covid1["confirmados_0_9_f"] = data_covid1.loc[:,["confirmados_0_9_f"]].diff()
data_covid1["confirmados_10_19_m"] = data_covid1.loc[:,["confirmados_10_19_m"]].diff()
data_covid1["confirmados_10_19_f"] = data_covid1.loc[:,["confirmados_10_19_f"]].diff()
data_covid1["confirmados_20_29_m"] = data_covid1.loc[:,["confirmados_20_29_m"]].diff()
data_covid1["confirmados_20_29_f"] = data_covid1.loc[:,["confirmados_20_29_f"]].diff()
data_covid1["confirmados_30_39_m"] = data_covid1.loc[:,["confirmados_30_39_m"]].diff()
data_covid1["confirmados_30_39_f"] = data_covid1.loc[:,["confirmados_30_39_f"]].diff()
data_covid1["confirmados_40_49_m"] = data_covid1.loc[:,["confirmados_40_49_m"]].diff()
data_covid1["confirmados_40_49_f"] = data_covid1.loc[:,["confirmados_40_49_f"]].diff()
data_covid1["confirmados_50_59_m"] = data_covid1.loc[:,["confirmados_50_59_m"]].diff()
data_covid1["confirmados_50_59_f"] = data_covid1.loc[:,["confirmados_50_59_f"]].diff()
data_covid1["confirmados_60_69_m"] = data_covid1.loc[:,["confirmados_60_69_m"]].diff()
data_covid1["confirmados_60_69_f"] = data_covid1.loc[:,["confirmados_60_69_f"]].diff()
data_covid1["confirmados_70_79_m"] = data_covid1.loc[:,["confirmados_70_79_m"]].diff()
data_covid1["confirmados_70_79_f"] = data_covid1.loc[:,["confirmados_70_79_f"]].diff()
data_covid1["confirmados_80_plus_m"] = data_covid1.loc[:,["confirmados_80_plus_m"]].diff()
data_covid1["confirmados_80_plus_f"] = data_covid1.loc[:,["confirmados_80_plus_f"]].diff()
data_covid1["obitos_arsnorte"] = data_covid1.loc[:,["obitos_arsnorte"]].diff()
data_covid1["obitos_arscentro"] = data_covid1.loc[:,["obitos_arscentro"]].diff()
data_covid1["obitos_arslvt"] = data_covid1.loc[:,["obitos_arslvt"]].diff()
data_covid1["obitos_arsalentejo"] = data_covid1.loc[:,["obitos_arsalentejo"]].diff()
data_covid1["obitos_arsalgarve"] = data_covid1.loc[:,["obitos_arsalgarve"]].diff()
data_covid1["obitos_acores"] = data_covid1.loc[:,["obitos_acores"]].diff()
data_covid1["obitos_madeira"] = data_covid1.loc[:,["obitos_madeira"]].diff()
data_covid1["obitos_0_9_m"] = data_covid1.loc[:,["obitos_0_9_m"]].diff()
data_covid1["obitos_0_9_f"] = data_covid1.loc[:,["obitos_0_9_f"]].diff()
data_covid1["obitos_10_19_m"] = data_covid1.loc[:,["obitos_10_19_m"]].diff()
data_covid1["obitos_10_19_f"] = data_covid1.loc[:,["obitos_10_19_f"]].diff()
data_covid1["obitos_20_29_m"] = data_covid1.loc[:,["obitos_20_29_m"]].diff()
data_covid1["obitos_20_29_f"] = data_covid1.loc[:,["obitos_20_29_f"]].diff()
data_covid1["obitos_30_39_m"] = data_covid1.loc[:,["obitos_30_39_m"]].diff()
data_covid1["obitos_30_39_f"] = data_covid1.loc[:,["obitos_30_39_f"]].diff()
data_covid1["obitos_40_49_m"] = data_covid1.loc[:,["obitos_40_49_m"]].diff()
data_covid1["obitos_40_49_f"] = data_covid1.loc[:,["obitos_40_49_f"]].diff()
data_covid1["obitos_50_59_m"] = data_covid1.loc[:,["obitos_50_59_m"]].diff()
data_covid1["obitos_50_59_f"] = data_covid1.loc[:,["obitos_50_59_f"]].diff()
data_covid1["obitos_60_69_m"] = data_covid1.loc[:,["obitos_60_69_m"]].diff()
data_covid1["obitos_60_69_f"] = data_covid1.loc[:,["obitos_60_69_f"]].diff()
data_covid1["obitos_70_79_m"] = data_covid1.loc[:,["obitos_70_79_m"]].diff()
data_covid1["obitos_70_79_f"] = data_covid1.loc[:,["obitos_70_79_f"]].diff()
data_covid1["obitos_80_plus_m"] = data_covid1.loc[:,["obitos_80_plus_m"]].diff()
data_covid1["obitos_80_plus_f"] = data_covid1.loc[:,["obitos_80_plus_f"]].diff()

In [168]:
#df = data_covid1.groupby([pd.Grouper(key='data', freq='1M')])['obitos'].sum().reset_index().sort_values('data')
df = data_covid1.groupby([pd.Grouper(key='Date', freq='M')]).sum()
df

,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,obitos,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
Date,,,,,,,,,,,,,,,,,,,,,
2020-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-03-31,651.0,127.0,222.0,5.0,21.0,7.0,2.0,7443,0.0,20.0,...,0.0,0.0,0.0,1.0,5.0,2.0,7.0,5.0,46009.0,3764.0
2020-04-30,-459.0,-78.0,-102.0,-1.0,-20.0,-5.0,-2.0,17249,49.0,-4.0,...,1.0,0.0,0.0,0.0,-2.0,-1.0,-2.0,0.0,495313.0,26940.0
2020-05-31,-171.0,-44.0,148.0,-4.0,2.0,-2.0,0.0,7808,174.0,-2.0,...,-1.0,0.0,0.0,-1.0,-3.0,0.0,3.0,-1.0,620568.0,17758.0
2020-06-30,-1.0,5.0,-50.0,7.0,0.0,0.0,1.0,9671,77.0,-6.0,...,0.0,0.0,0.0,1.0,1.0,0.0,-5.0,-2.0,371917.0,10941.0
2020-07-31,29.0,-6.0,-90.0,10.0,2.0,1.0,-1.0,8901,43.0,0.0,...,0.0,0.0,0.0,0.0,-1.0,2.0,-1.0,-1.0,417394.0,12209.0
2020-08-31,34.0,3.0,9.0,-10.0,2.0,2.0,0.0,6940,-267.0,-5.0,...,0.0,0.0,0.0,-1.0,0.0,-3.0,-1.0,1.0,399994.0,9533.0
2020-09-30,211.0,75.0,261.0,-4.0,34.0,2.0,2.0,17530,261.0,5.0,...,0.0,0.0,1.0,0.0,0.0,0.0,5.0,-1.0,578124.0,12488.0
2020-10-31,1606.0,470.0,1008.0,58.0,39.0,-2.0,3.0,65737,2494.0,31.0,...,0.0,0.0,0.0,3.0,2.0,3.0,7.0,16.0,1180561.0,30326.0
2020-11-30,-105.0,-145.0,-567.0,87.0,-46.0,29.0,2.0,156782,577.0,39.0,...,1.0,2.0,0.0,5.0,7.0,7.0,12.0,4.0,2325036.0,72843.0
2020-12-31,793.0,1008.0,1962.0,376.0,185.0,4.0,37.0,115617,-148.0,-2.0,...,0.0,1.0,0.0,-3.0,-4.0,-1.0,9.0,-5.0,2193454.0,80836.0
2021-01-31,63.0,-30.0,2033.0,-270.0,14.0,4.0,57.0,306838,4251.0,227.0,...,1.0,1.0,9.0,16.0,14.0,20.0,86.0,81.0,4014750.0,128663.0
2021-02-28,-2422.0,-1288.0,-4577.0,-204.0,-201.0,-22.0,-66.0,84046,-5847.0,-262.0,...,-2.0,-3.0,-7.0,-16.0,-18.0,-17.0,-113.0,-85.0,3109696.0,109558.0
2021-03-31,-19.0,-23.0,14.0,-41.0,3.0,-10.0,-25.0,17160,-957.0,-38.0,...,0.0,-1.0,-3.0,-4.0,-1.0,-11.0,-7.0,-11.0,1347318.0,25009.0
2021-04-30,75.0,-21.0,-82.0,7.0,-16.0,21.0,9.0,10533,-175.0,-2.0,...,-130.0,-331.0,-460.0,-1059.0,-1328.0,-2277.0,-6038.0,-5121.0,539058.0,7445.0

In [169]:
temp1 = pd.read_csv("./datasets_monthly/temp_portugal_01012020_31032020.csv", sep = ",")
temp2 = pd.read_csv("./datasets_monthly/temp_portugal_01042020_30062020.csv", sep = ",")
temp3 = pd.read_csv("./datasets_monthly/temp_portugal_01072020_30092020.csv", sep = ",")
temp4 = pd.read_csv("./datasets_monthly/temp_portugal_01102020_31122020.csv", sep = ",")
temp5 = pd.read_csv("./datasets_monthly/temp_portugal_01012021_31032021.csv", sep = ",")
temp6 = pd.read_csv("./datasets_monthly/temp_portugal_042021.csv", sep = ",")

df_temp = temp1.append(temp2, ignore_index = True)
df_temp = df_temp.append(temp3, ignore_index = True)
df_temp = df_temp.append(temp4, ignore_index = True)
df_temp = df_temp.append(temp5, ignore_index = True)
df_temp = df_temp.append(temp6, ignore_index = True)

In [170]:
def condition_ohe_rain(condition):
    res =0
    if(condition == 'Rain' or condition == 'Rain, Partially cloudy'):
        res=1

    return res

def condition_ohe_clear(condition):
    res =0
    if(condition == 'Clear'):
        res=1

    return res


def condition_ohe_cloudy(condition):
    res =0
    if(condition == 'Rain, Partially cloudy' or condition == 'Partially cloudy'):
        res=1

    return res

In [171]:
df_temp1 = df_temp.copy()
df_temp1 = df_temp1.drop(columns=['Name','Wind Chill','Heat Index', 'Wind Gust', 'Snow', 'Snow Depth'])
#print(df_aux.shape)

#rename columns
df_temp1.columns = ['Date', 'Max_Temp','Min_Temp','Temperature','Precipitation','Wind_Speed','Wind_Direction','Visibility','Cloud_Cover','Relative_Humidity','Conditions']

#one hot encoding weather conditions
df_temp1['Rain'] = np.nan
df_temp1['Clear'] = np.nan
df_temp1['Partially_cloudy'] = np.nan
    
df_temp1['Rain'] = df_temp1.apply(lambda x: condition_ohe_rain(x['Conditions']), axis=1)
df_temp1['Clear'] = df_temp1.apply(lambda x: condition_ohe_clear(x['Conditions']), axis=1)
df_temp1['Partially_cloudy'] = df_temp1.apply(lambda x: condition_ohe_cloudy(x['Conditions']), axis=1)

df_temp1 = df_temp1.drop(columns='Conditions')

df_temp1["Date"] = pd.to_datetime(df_temp1['Date'],format="%m/%d/%Y")

In [173]:
df_covid = pd.merge(df,df_temp1, on='Date', how='left')
df_covid

,Date,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,Temperature,Precipitation,Wind_Speed,Wind_Direction,Visibility,Cloud_Cover,Relative_Humidity,Rain,Clear,Partially_cloudy
0,2020-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,15.1,3.53,24.7,253.13,9.6,6.8,82.29,1,0,0
1,2020-03-31,651.0,127.0,222.0,5.0,21.0,7.0,2.0,7443,0.0,...,9.2,0.61,27.7,141.30,10.5,4.4,74.34,1,0,0
2,2020-04-30,-459.0,-78.0,-102.0,-1.0,-20.0,-5.0,-2.0,17249,49.0,...,16.9,0.10,24.1,237.79,10.3,5.8,80.38,1,0,0
3,2020-05-31,-171.0,-44.0,148.0,-4.0,2.0,-2.0,0.0,7808,174.0,...,21.7,0.00,19.1,262.58,10.5,5.9,69.51,0,1,0
4,2020-06-30,-1.0,5.0,-50.0,7.0,0.0,0.0,1.0,9671,77.0,...,21.8,0.00,22.8,325.75,11.6,4.4,71.59,0,1,0
5,2020-07-31,29.0,-6.0,-90.0,10.0,2.0,1.0,-1.0,8901,43.0,...,23.6,0.00,23.3,311.58,11.4,0.1,60.13,0,1,0
6,2020-08-31,34.0,3.0,9.0,-10.0,2.0,2.0,0.0,6940,-267.0,...,23.4,0.00,19.0,186.17,12.8,1.6,36.84,0,1,0
7,2020-09-30,211.0,75.0,261.0,-4.0,34.0,2.0,2.0,17530,261.0,...,19.2,0.00,22.1,334.08,10.9,3.1,70.47,0,1,0
8,2020-10-31,1606.0,470.0,1008.0,58.0,39.0,-2.0,3.0,65737,2494.0,...,17.5,0.00,15.4,179.83,10.3,4.4,82.49,0,1,0
9,2020-11-30,-105.0,-145.0,-567.0,87.0,-46.0,29.0,2.0,156782,577.0,...,12.9,1.18,18.6,70.75,10.2,11.5,88.60,1,0,0
10,2020-12-31,793.0,1008.0,1962.0,376.0,185.0,4.0,37.0,115617,-148.0,...,10.4,3.90,20.8,271.54,11.1,8.8,82.96,1,0,0
11,2021-01-31,63.0,-30.0,2033.0,-270.0,14.0,4.0,57.0,306838,4251.0,...,14.8,2.25,25.9,269.08,8.0,9.8,93.22,1,0,0
12,2021-02-28,-2422.0,-1288.0,-4577.0,-204.0,-201.0,-22.0,-66.0,84046,-5847.0,...,13.8,0.00,12.6,190.96,10.0,1.2,78.87,0,1,0
13,2021-03-31,-19.0,-23.0,14.0,-41.0,3.0,-10.0,-25.0,17160,-957.0,...,18.8,0.00,22.0,121.61,10.4,0.3,55.66,0,1,0
14,2021-04-30,75.0,-21.0,-82.0,7.0,-16.0,21.0,9.0,10533,-175.0,...,13.7,0.00,23.6,323.18,10.0,34.4,62.32,0,0,1