In [91]:
import numpy as np
import pandas as pd

**Mortes por covid, incluindo internamentos**

In [92]:
data_covid = pd.read_csv("./datasets_monthly/data.csv", sep = ",")

data_covid

,data,data_dados,confirmados,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,...,obitos_m,confirmados_desconhecidos_m,confirmados_desconhecidos_f,ativos,internados_enfermaria,confirmados_desconhecidos,incidencia_nacional,incidencia_continente,rt_nacional,rt_continente
0,26-02-2020,26-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27-02-2020,27-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28-02-2020,28-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29-02-2020,29-02-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-03-2020,01-03-2020 00:00,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,17-04-2021,17-04-2021 00:00,830560,333542,118079,314568,29554,21348,4507,8962,...,8903.0,NaN,NaN,25344.0,312.0,302.0,71.6,68.0,1.05,1.04
417,18-04-2021,18-04-2021 00:00,831001,333735,118125,314677,29559,21386,4540,8979,...,8903.0,NaN,NaN,25387.0,319.0,302.0,71.6,68.0,1.05,1.04
418,19-04-2021,19-04-2021 00:00,831221,333832,118149,314733,29568,21391,4554,8994,...,8903.0,NaN,NaN,25059.0,342.0,302.0,71.8,68.1,1.00,1.00
419,20-04-2021,20-04-2021 00:00,831645,333961,118183,314886,29609,21419,4570,9017,...,8906.0,NaN,NaN,24576.0,316.0,305.0,71.8,68.1,1.00,1.00
420,21-04-2021,21-04-2021 00:00,832255,334246,118236,315075,29625,21438,4599,9036,...,8906.0,NaN,NaN,24653.0,287.0,303.0,72.7,68.9,0.98,0.99

In [93]:
data_covid1 = data_covid.drop(columns=['data_dados', 'confirmados', 'confirmados_estrangeiro', 'sintomas_cefaleia',
                                        'sintomas_fraqueza_generalizada','sintomas_dificuldade_respiratoria','sintomas_dores_musculares',
                                        'sintomas_febre','sintomas_tosse', 'lab', 'suspeitos', 'vigilancia',
                                        'n_confirmados', 'cadeias_transmissao', 'transmissao_importada',
                                        'obitos_estrangeiro', 'recuperados_arsnorte','recuperados_arscentro',
                                        'recuperados_arslvt','recuperados_arsalentejo',
                                        'recuperados_arsalgarve','recuperados_acores', 'recuperados_madeira',
                                        'recuperados_estrangeiro','confirmados_desconhecidos_m','confirmados_desconhecidos_f',
                                        'incidencia_nacional','incidencia_continente','rt_nacional', 'rt_continente',
                                        'obitos_f', 'obitos_m','confirmados_desconhecidos','confirmados_f','confirmados_m'], inplace=False)

#somar colunas casos confirmados com mesma faixa etaria ignorando sexo
#data_covid1['confirmados_0_9'] = data_covid1.apply(lambda x: x['confirmados_0_9_f'] + x['confirmados_0_9_m'], axis=1)
#data_covid1['confirmados_10_19'] = data_covid1.apply(lambda x: x['confirmados_10_19_f'] + x['confirmados_10_19_m'], axis=1)
#data_covid1['confirmados_20_29'] = data_covid1.apply(lambda x: x['confirmados_20_29_f'] + x['confirmados_20_29_m'], axis=1)
#data_covid1['confirmados_30_39'] = data_covid1.apply(lambda x: x['confirmados_30_39_f'] + x['confirmados_30_39_m'], axis=1)
#data_covid1['confirmados_40_49'] = data_covid1.apply(lambda x: x['confirmados_40_49_f'] + x['confirmados_40_49_m'], axis=1)
#data_covid1['confirmados_50_59'] = data_covid1.apply(lambda x: x['confirmados_50_59_f'] + x['confirmados_50_59_m'], axis=1)
#data_covid1['confirmados_60_69'] = data_covid1.apply(lambda x: x['confirmados_60_69_f'] + x['confirmados_60_69_m'], axis=1)
#data_covid1['confirmados_70_79'] = data_covid1.apply(lambda x: x['confirmados_70_79_f'] + x['confirmados_70_79_m'], axis=1)
#data_covid1['confirmados_80_plus'] = data_covid1.apply(lambda x: x['confirmados_80_plus_f'] + x['confirmados_80_plus_m'], axis=1)

#data_covid1 = data_covid1.drop(columns=['confirmados_0_9_f','confirmados_0_9_m',
#                            'confirmados_10_19_f','confirmados_10_19_m',
#                            'confirmados_20_29_f','confirmados_20_29_m',
#                            'confirmados_30_39_f','confirmados_30_39_m',
#                            'confirmados_40_49_f','confirmados_40_49_m',
#                            'confirmados_50_59_f','confirmados_50_59_m',
#                            'confirmados_60_69_f','confirmados_60_69_m',
#                            'confirmados_70_79_f','confirmados_70_79_m',
#                            'confirmados_80_plus_f','confirmados_80_plus_m'], inplace=False)


#somar colunas obitos confirmados com mesma faixa etaria ignorando sexo
#data_covid1['obitos_0_9'] = data_covid1.apply(lambda x: x['obitos_0_9_f'] + x['obitos_0_9_m'], axis=1)
#data_covid1['obitos_10_19'] = data_covid1.apply(lambda x: x['obitos_10_19_f'] + x['obitos_10_19_m'], axis=1)
#data_covid1['obitos_20_29'] = data_covid1.apply(lambda x: x['obitos_20_29_f'] + x['obitos_20_29_m'], axis=1)
#data_covid1['obitos_30_39'] = data_covid1.apply(lambda x: x['obitos_30_39_f'] + x['obitos_30_39_m'], axis=1)
#data_covid1['obitos_40_49'] = data_covid1.apply(lambda x: x['obitos_40_49_f'] + x['obitos_40_49_m'], axis=1)
#data_covid1['obitos_50_59'] = data_covid1.apply(lambda x: x['obitos_50_59_f'] + x['obitos_50_59_m'], axis=1)
#data_covid1['obitos_60_69'] = data_covid1.apply(lambda x: x['obitos_60_69_f'] + x['obitos_60_69_m'], axis=1)
#data_covid1['obitos_70_79'] = data_covid1.apply(lambda x: x['obitos_70_79_f'] + x['obitos_70_79_m'], axis=1)
#data_covid1['obitos_80_plus'] = data_covid1.apply(lambda x: x['obitos_80_plus_f'] + x['obitos_80_plus_m'], axis=1)

#data_covid1 = data_covid1.drop(columns=['obitos_0_9_f','obitos_0_9_m',
#                            'obitos_10_19_f','obitos_10_19_m',
#                            'obitos_20_29_f','obitos_20_29_m',
#                            'obitos_30_39_f','obitos_30_39_m',
#                            'obitos_40_49_f','obitos_40_49_m',
#                            'obitos_50_59_f','obitos_50_59_m',
#                            'obitos_60_69_f','obitos_60_69_m',
#                            'obitos_70_79_f','obitos_70_79_m',
#                            'obitos_80_plus_f','obitos_80_plus_m'], inplace=False)

    
data_covid1.head()

,data,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
0,26-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-03-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
data_covid1.columns = ['Data', 'confirmados_arsnorte', 'confirmados_arscentro','confirmados_arslvt', 'confirmados_arsalentejo', 'confirmados_arsalgarve', 'confirmados_acores', 'confirmados_madeira','confirmados_novos', 'recuperados', 'obitos', 'internados', 'internados_uci',
                       'confirmados_0_9_f',
                       'confirmados_0_9_m',
                       'confirmados_10_19_f', 
                       'confirmados_10_19_m', 
                       'confirmados_20_29_f', 
                       'confirmados_20_29_m', 
                       'confirmados_30_39_f', 
                       'confirmados_30_39_m', 
                       'confirmados_40_49_f', 
                       'confirmados_40_49_m', 
                       'confirmados_50_59_f', 
                       'confirmados_50_59_m', 
                       'confirmados_60_69_f', 
                       'confirmados_60_69_m', 
                       'confirmados_70_79_f', 
                       'confirmados_70_79_m', 
                       'confirmados_80_plus_f', 
                       'confirmados_80_plus_m', 
                       'obitos_arsnorte', 'obitos_arscentro', 'obitos_arslvt', 'obitos_arsalentejo', 'obitos_arsalgarve', 'obitos_acores', 'obitos_madeira', 
                       'obitos_0_9_f', 
                       'obitos_0_9_m', 
                       'obitos_10_19_f', 
                       'obitos_10_19_m', 
                       'obitos_20_29_f', 
                       'obitos_20_29_m', 
                       'obitos_30_39_f', 
                       'obitos_30_39_m', 
                       'obitos_40_49_f', 
                       'obitos_40_49_m', 
                       'obitos_50_59_f', 
                       'obitos_50_59_m', 
                       'obitos_60_69_f', 
                       'obitos_60_69_m', 
                       'obitos_70_79_f', 
                       'obitos_70_79_m', 
                       'obitos_80_plus_f', 
                       'obitos_80_plus_m', 
                       'ativos', 'internados_enfermaria']
data_covid1

,Data,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
0,26-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29-02-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-03-2020,0,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,17-04-2021,333542,118079,314568,29554,21348,4507,8962,649,788274,...,130.0,331.0,459.0,1057.0,1326.0,2274.0,6035.0,5120.0,25344.0,312.0
417,18-04-2021,333735,118125,314677,29559,21386,4540,8979,441,788669,...,130.0,331.0,459.0,1057.0,1328.0,2274.0,6036.0,5120.0,25387.0,319.0
418,19-04-2021,333832,118149,314733,29568,21391,4554,8994,220,789216,...,130.0,331.0,459.0,1057.0,1328.0,2274.0,6037.0,5120.0,25059.0,342.0
419,20-04-2021,333961,118183,314886,29609,21419,4570,9017,424,790118,...,130.0,331.0,460.0,1058.0,1328.0,2276.0,6038.0,5120.0,24576.0,316.0
420,21-04-2021,334246,118236,315075,29625,21438,4599,9036,610,790650,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24653.0,287.0

In [95]:
data_covid1 = data_covid1.fillna(0)
data_covid1.head()

,Data,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
0,26-02-2020,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,27-02-2020,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28-02-2020,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,29-02-2020,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,01-03-2020,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [96]:
data_covid1['Data'] = pd.to_datetime(data_covid1['Data'],format="%d-%m-%Y")

data_covid1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 58 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Data                     421 non-null    datetime64[ns]
 1   confirmados_arsnorte     421 non-null    int64
 2   confirmados_arscentro    421 non-null    int64
 3   confirmados_arslvt       421 non-null    int64
 4   confirmados_arsalentejo  421 non-null    int64
 5   confirmados_arsalgarve   421 non-null    int64
 6   confirmados_acores       421 non-null    int64
 7   confirmados_madeira      421 non-null    int64
 8   confirmados_novos        421 non-null    int64
 9   recuperados              421 non-null    int64
 10  obitos                   421 non-null    int64
 11  internados               421 non-null    float64
 12  internados_uci           421 non-null    float64
 13  confirmados_0_9_f        421 non-null    float64
 14  confirmados_0_9_m        421 non-null    float64
 15  confirmados_10_19_f      421 non-null    float64
 16  confirmados_10_19_m      421 non-null    float64
 17  confirmados_20_29_f      421 non-null    float64
 18  confirmados_20_29_m      421 non-null    float64
 19  confirmados_30_39_f      421 non-null    float64
 20  confirmados_30_39_m      421 non-null    float64
 21  confirmados_40_49_f      421 non-null    float64
 22  confirmados_40_49_m      421 non-null    float64
 23  confirmados_50_59_f      421 non-null    float64
 24  confirmados_50_59_m      421 non-null    float64
 25  confirmados_60_69_f      421 non-null    float64
 26  confirmados_60_69_m      421 non-null    float64
 27  confirmados_70_79_f      421 non-null    float64
 28  confirmados_70_79_m      421 non-null    float64
 29  confirmados_80_plus_f    421 non-null    float64
 30  confirmados_80_plus_m    421 non-null    float64
 31  obitos_arsnorte          421 non-null    int64
 32  obitos_arscentro         421 non-null    int64
 33  obitos_arslvt            421 non-null    int64
 34  obitos_arsalentejo       421 non-null    int64
 35  obitos_arsalgarve        421 non-null    int64
 36  obitos_acores            421 non-null    int64
 37  obitos_madeira           421 non-null    int64
 38  obitos_0_9_f             421 non-null    float64
 39  obitos_0_9_m             421 non-null    float64
 40  obitos_10_19_f           421 non-null    float64
 41  obitos_10_19_m           421 non-null    float64
 42  obitos_20_29_f           421 non-null    float64
 43  obitos_20_29_m           421 non-null    float64
 44  obitos_30_39_f           421 non-null    float64
 45  obitos_30_39_m           421 non-null    float64
 46  obitos_40_49_f           421 non-null    float64
 47  obitos_40_49_m           421 non-null    float64
 48  obitos_50_59_f           421 non-null    float64
 49  obitos_50_59_m           421 non-null    float64
 50  obitos_60_69_f           421 non-null    float64
 51  obitos_60_69_m           421 non-null    float64
 52  obitos_70_79_f           421 non-null    float64
 53  obitos_70_79_m           421 non-null    float64
 54  obitos_80_plus_f         421 non-null    float64
 55  obitos_80_plus_m         421 non-null    float64
 56  ativos                   421 non-null    float64
 57  internados_enfermaria    421 non-null    float64
dtypes: datetime64[ns](1), float64(40), int64(17)
memory usage: 190.9 KB

In [97]:
data_covid1["confirmados_arsnorte"] = data_covid1.loc[:,["confirmados_arsnorte"]].diff()
data_covid1["confirmados_arscentro"] = data_covid1.loc[:,["confirmados_arscentro"]].diff()
data_covid1["confirmados_arslvt"] = data_covid1.loc[:,["confirmados_arslvt"]].diff()
data_covid1["confirmados_arsalentejo"] = data_covid1.loc[:,["confirmados_arsalentejo"]].diff()
data_covid1["confirmados_arsalgarve"] = data_covid1.loc[:,["confirmados_arsalgarve"]].diff()
data_covid1["confirmados_acores"] = data_covid1.loc[:,["confirmados_acores"]].diff()
data_covid1["confirmados_madeira"] = data_covid1.loc[:,["confirmados_madeira"]].diff()
data_covid1["recuperados"] = data_covid1.loc[:,["recuperados"]].diff()
data_covid1["obitos"] = data_covid1.loc[:,["obitos"]].diff()
data_covid1["confirmados_0_9_f"] = data_covid1.loc[:,["confirmados_0_9_f"]].diff()
data_covid1["confirmados_0_9_m"] = data_covid1.loc[:,["confirmados_0_9_m"]].diff()
data_covid1["confirmados_10_19_f"] = data_covid1.loc[:,["confirmados_10_19_f"]].diff()
data_covid1["confirmados_10_19_m"] = data_covid1.loc[:,["confirmados_10_19_m"]].diff()
data_covid1["confirmados_20_29_f"] = data_covid1.loc[:,["confirmados_20_29_f"]].diff()
data_covid1["confirmados_20_29_m"] = data_covid1.loc[:,["confirmados_20_29_m"]].diff()
data_covid1["confirmados_30_39_f"] = data_covid1.loc[:,["confirmados_30_39_f"]].diff()
data_covid1["confirmados_30_39_m"] = data_covid1.loc[:,["confirmados_30_39_m"]].diff()
data_covid1["confirmados_40_49_f"] = data_covid1.loc[:,["confirmados_40_49_f"]].diff()
data_covid1["confirmados_40_49_m"] = data_covid1.loc[:,["confirmados_40_49_m"]].diff()
data_covid1["confirmados_50_59_f"] = data_covid1.loc[:,["confirmados_50_59_f"]].diff()
data_covid1["confirmados_50_59_m"] = data_covid1.loc[:,["confirmados_50_59_m"]].diff()
data_covid1["confirmados_60_69_f"] = data_covid1.loc[:,["confirmados_60_69_f"]].diff()
data_covid1["confirmados_60_69_m"] = data_covid1.loc[:,["confirmados_60_69_m"]].diff()
data_covid1["confirmados_70_79_f"] = data_covid1.loc[:,["confirmados_70_79_f"]].diff()
data_covid1["confirmados_70_79_m"] = data_covid1.loc[:,["confirmados_70_79_m"]].diff()
data_covid1["confirmados_80_plus_f"] = data_covid1.loc[:,["confirmados_80_plus_f"]].diff()
data_covid1["confirmados_80_plus_m"] = data_covid1.loc[:,["confirmados_80_plus_m"]].diff()
data_covid1["obitos_arsnorte"] = data_covid1.loc[:,["obitos_arsnorte"]].diff()
data_covid1["obitos_arscentro"] = data_covid1.loc[:,["obitos_arscentro"]].diff()
data_covid1["obitos_arslvt"] = data_covid1.loc[:,["obitos_arslvt"]].diff()
data_covid1["obitos_arsalentejo"] = data_covid1.loc[:,["obitos_arsalentejo"]].diff()
data_covid1["obitos_arsalgarve"] = data_covid1.loc[:,["obitos_arsalgarve"]].diff()
data_covid1["obitos_acores"] = data_covid1.loc[:,["obitos_acores"]].diff()
data_covid1["obitos_madeira"] = data_covid1.loc[:,["obitos_madeira"]].diff()
data_covid1["obitos_0_9_f"] = data_covid1.loc[:,["obitos_0_9_f"]].diff()
data_covid1["obitos_0_9_m"] = data_covid1.loc[:,["obitos_0_9_m"]].diff()
data_covid1["obitos_10_19_f"] = data_covid1.loc[:,["obitos_10_19_f"]].diff()
data_covid1["obitos_10_19_m"] = data_covid1.loc[:,["obitos_10_19_m"]].diff()
data_covid1["obitos_20_29_f"] = data_covid1.loc[:,["obitos_20_29_f"]].diff()
data_covid1["obitos_20_29_m"] = data_covid1.loc[:,["obitos_20_29_m"]].diff()
data_covid1["obitos_30_39_f"] = data_covid1.loc[:,["obitos_30_39_f"]].diff()
data_covid1["obitos_30_39_m"] = data_covid1.loc[:,["obitos_30_39_m"]].diff()
data_covid1["obitos_40_49_f"] = data_covid1.loc[:,["obitos_40_49_f"]].diff()
data_covid1["obitos_40_49_m"] = data_covid1.loc[:,["obitos_40_49_m"]].diff()
data_covid1["obitos_50_59_f"] = data_covid1.loc[:,["obitos_50_59_f"]].diff()
data_covid1["obitos_50_59_m"] = data_covid1.loc[:,["obitos_50_59_m"]].diff()
data_covid1["obitos_60_69_f"] = data_covid1.loc[:,["obitos_60_69_f"]].diff()
data_covid1["obitos_60_69_m"] = data_covid1.loc[:,["obitos_60_69_m"]].diff()
data_covid1["obitos_70_79_f"] = data_covid1.loc[:,["obitos_70_79_f"]].diff()
data_covid1["obitos_70_79_m"] = data_covid1.loc[:,["obitos_70_79_m"]].diff()
data_covid1["obitos_80_plus_f"] = data_covid1.loc[:,["obitos_80_plus_f"]].diff()
data_covid1["obitos_80_plus_m"] = data_covid1.loc[:,["obitos_80_plus_m"]].diff()

In [98]:
#df = data_covid1.groupby([pd.Grouper(key='data', freq='1M')])['obitos'].sum().reset_index().sort_values('data')
df = data_covid1.groupby([pd.Grouper(key='Data', freq='M')]).sum()
df

,confirmados_arsnorte,confirmados_arscentro,confirmados_arslvt,confirmados_arsalentejo,confirmados_arsalgarve,confirmados_acores,confirmados_madeira,confirmados_novos,recuperados,obitos,...,obitos_50_59_f,obitos_50_59_m,obitos_60_69_f,obitos_60_69_m,obitos_70_79_f,obitos_70_79_m,obitos_80_plus_f,obitos_80_plus_m,ativos,internados_enfermaria
Data,,,,,,,,,,,,,,,,,,,,,
2020-02-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-03-31,4452.0,911.0,1799.0,50.0,137.0,48.0,46.0,7443,43.0,160.0,...,1.0,5.0,1.0,16.0,13.0,25.0,47.0,50.0,46009.0,3764.0
2020-04-30,10274.0,2478.0,4016.0,168.0,194.0,79.0,40.0,17249,1476.0,829.0,...,7.0,16.0,30.0,40.0,68.0,89.0,333.0,238.0,495313.0,26940.0
2020-05-31,2034.0,355.0,5327.0,41.0,39.0,8.0,4.0,7808,17890.0,421.0,...,6.0,10.0,12.0,26.0,30.0,49.0,161.0,119.0,620568.0,17758.0
2020-06-30,761.0,366.0,8053.0,225.0,248.0,15.0,3.0,9671,8096.0,166.0,...,1.0,4.0,3.0,16.0,10.0,20.0,57.0,51.0,371917.0,10941.0
2020-07-31,1154.0,329.0,6872.0,250.0,265.0,18.0,13.0,8901,8978.0,159.0,...,2.0,3.0,2.0,8.0,9.0,24.0,61.0,46.0,417394.0,12209.0
2020-08-31,2184.0,368.0,3854.0,210.0,229.0,44.0,51.0,6940,5478.0,87.0,...,0.0,3.0,1.0,4.0,9.0,13.0,25.0,30.0,399994.0,9533.0
2020-09-30,6170.0,1351.0,8771.0,558.0,551.0,62.0,67.0,17530,6569.0,149.0,...,1.0,0.0,7.0,6.0,12.0,18.0,59.0,44.0,578124.0,12488.0
2020-10-31,36298.0,6129.0,20651.0,1232.0,1116.0,95.0,216.0,65737,31750.0,536.0,...,6.0,10.0,13.0,39.0,34.0,73.0,183.0,174.0,1180561.0,30326.0
2020-11-30,93158.0,17389.0,39180.0,3424.0,2524.0,653.0,454.0,156782,132662.0,1998.0,...,13.0,46.0,42.0,114.0,169.0,254.0,712.0,628.0,2325036.0,72843.0
2020-12-31,53479.0,18045.0,35216.0,4965.0,2395.0,810.0,707.0,115617,121334.0,2401.0,...,17.0,31.0,49.0,133.0,172.0,314.0,909.0,749.0,2193454.0,80836.0
2021-01-31,96268.0,54814.0,128298.0,13790.0,9540.0,1674.0,2454.0,306838,192135.0,5576.0,...,39.0,97.0,148.0,342.0,427.0,714.0,2033.0,1707.0,4014750.0,128663.0
2021-02-28,20072.0,12422.0,42497.0,3546.0,2860.0,246.0,2403.0,84046,192566.0,3835.0,...,28.0,82.0,128.0,259.0,324.0,565.0,1282.0,1116.0,3109696.0,109558.0
2021-03-31,4369.0,2206.0,6928.0,621.0,577.0,311.0,2148.0,17160,59233.0,531.0,...,8.0,23.0,20.0,41.0,43.0,96.0,148.0,144.0,1347318.0,25009.0
2021-04-30,3573.0,1073.0,3613.0,545.0,763.0,536.0,430.0,10533,12440.0,104.0,...,-129.0,-330.0,-456.0,-1044.0,-1320.0,-2254.0,-6010.0,-5096.0,539058.0,7445.0

In [99]:
temp1 = pd.read_csv("./datasets_monthly/temp_portugal_01012020_31032020.csv", sep = ",")
temp2 = pd.read_csv("./datasets_monthly/temp_portugal_01042020_30062020.csv", sep = ",")
temp3 = pd.read_csv("./datasets_monthly/temp_portugal_01072020_30092020.csv", sep = ",")
temp4 = pd.read_csv("./datasets_monthly/temp_portugal_01102020_31122020.csv", sep = ",")
temp5 = pd.read_csv("./datasets_monthly/temp_portugal_01012021_31032021.csv", sep = ",")
temp6 = pd.read_csv("./datasets_monthly/temp_portugal_042021.csv", sep = ",")

df_temp = temp1.append(temp2, ignore_index = True)
df_temp = df_temp.append(temp3, ignore_index = True)
df_temp = df_temp.append(temp4, ignore_index = True)
df_temp = df_temp.append(temp5, ignore_index = True)
df_temp = df_temp.append(temp6, ignore_index = True)

In [100]:
def condition_ohe_rain(condition):
    res =0
    if(condition == 'Rain' or condition == 'Rain, Partially cloudy'):
        res=1

    return res

def condition_ohe_clear(condition):
    res =0
    if(condition == 'Clear'):
        res=1

    return res


def condition_ohe_cloudy(condition):
    res =0
    if(condition == 'Rain, Partially cloudy' or condition == 'Partially cloudy'):
        res=1

    return res

In [101]:
df_temp1 = df_temp.copy()
df_temp1 = df_temp1.drop(columns=['Name',  'Wind Chill','Heat Index', 'Wind Gust', 'Snow', 'Snow Depth'])
#print(df_aux.shape)

#rename columns
df_temp1.columns = ['Data', 'Max_Temp','Min_Temp','Temperature','Precipitation','Wind_Speed','Wind_Direction','Visibility','Cloud_Cover','Relative_Humidity','Conditions']

#one hot encoding weather conditions
df_temp1['Rain'] = np.nan
df_temp1['Clear'] = np.nan
df_temp1['Partially_cloudy'] = np.nan
    
df_temp1['Rain'] = df_temp1.apply(lambda x: condition_ohe_rain(x['Conditions']), axis=1)
df_temp1['Clear'] = df_temp1.apply(lambda x: condition_ohe_clear(x['Conditions']), axis=1)
df_temp1['Partially_cloudy'] = df_temp1.apply(lambda x: condition_ohe_cloudy(x['Conditions']), axis=1)

df_temp1 = df_temp1.drop(columns='Conditions')

df_temp1["Data"] = pd.to_datetime(df_temp1['Data'],format="%m/%d/%Y")
df_temp1 = df_temp1.groupby([pd.Grouper(key='Data', freq='M')]).mean()

In [102]:
df_covid = pd.merge(df,df_temp1, on='Data', how='left')
df_covid = df_covid.fillna(0)
df_covid.columns

Index(['confirmados_arsnorte', 'confirmados_arscentro', 'confirmados_arslvt',
       'confirmados_arsalentejo', 'confirmados_arsalgarve',
       'confirmados_acores', 'confirmados_madeira', 'confirmados_novos',
       'recuperados', 'obitos', 'internados', 'internados_uci',
       'confirmados_0_9_f', 'confirmados_0_9_m', 'confirmados_10_19_f',
       'confirmados_10_19_m', 'confirmados_20_29_f', 'confirmados_20_29_m',
       'confirmados_30_39_f', 'confirmados_30_39_m', 'confirmados_40_49_f',
       'confirmados_40_49_m', 'confirmados_50_59_f', 'confirmados_50_59_m',
       'confirmados_60_69_f', 'confirmados_60_69_m', 'confirmados_70_79_f',
       'confirmados_70_79_m', 'confirmados_80_plus_f', 'confirmados_80_plus_m',
       'obitos_arsnorte', 'obitos_arscentro', 'obitos_arslvt',
       'obitos_arsalentejo', 'obitos_arsalgarve', 'obitos_acores',
       'obitos_madeira', 'obitos_0_9_f', 'obitos_0_9_m', 'obitos_10_19_f',
       'obitos_10_19_m', 'obitos_20_29_f', 'obitos_20_29_m', 'obitos_30_39_f',
       'obitos_30_39_m', 'obitos_40_49_f', 'obitos_40_49_m', 'obitos_50_59_f',
       'obitos_50_59_m', 'obitos_60_69_f', 'obitos_60_69_m', 'obitos_70_79_f',
       'obitos_70_79_m', 'obitos_80_plus_f', 'obitos_80_plus_m', 'ativos',
       'internados_enfermaria', 'Max_Temp', 'Min_Temp', 'Temperature',
       'Precipitation', 'Wind_Speed', 'Wind_Direction', 'Visibility',
       'Cloud_Cover', 'Relative_Humidity', 'Rain', 'Clear',
       'Partially_cloudy'],
      dtype='object')

In [90]:
df_covid.to_csv('./data_covid.csv', index = True)